// This file was generated by Prisma, and assumes you have installed the following:
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./src/db/schema.prisma",
  migrations: {
    path: "./src/db/migrations",
  },
  datasource: {
    url: process.env['DATABASE_URL'] || "",
  },
});
