
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CrmSyncEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model CrmSyncEvent
 * 
 */
export type CrmSyncEventModel = runtime.Types.Result.DefaultSelection<Prisma.$CrmSyncEventPayload>

export type AggregateCrmSyncEvent = {
  _count: CrmSyncEventCountAggregateOutputType | null
  _min: CrmSyncEventMinAggregateOutputType | null
  _max: CrmSyncEventMaxAggregateOutputType | null
}

export type CrmSyncEventMinAggregateOutputType = {
  id: string | null
  companyId: string | null
  status: boolean | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CrmSyncEventMaxAggregateOutputType = {
  id: string | null
  companyId: string | null
  status: boolean | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CrmSyncEventCountAggregateOutputType = {
  id: number
  companyId: number
  status: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CrmSyncEventMinAggregateInputType = {
  id?: true
  companyId?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type CrmSyncEventMaxAggregateInputType = {
  id?: true
  companyId?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type CrmSyncEventCountAggregateInputType = {
  id?: true
  companyId?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CrmSyncEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CrmSyncEvent to aggregate.
   */
  where?: Prisma.CrmSyncEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CrmSyncEvents to fetch.
   */
  orderBy?: Prisma.CrmSyncEventOrderByWithRelationInput | Prisma.CrmSyncEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CrmSyncEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CrmSyncEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CrmSyncEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CrmSyncEvents
  **/
  _count?: true | CrmSyncEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CrmSyncEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CrmSyncEventMaxAggregateInputType
}

export type GetCrmSyncEventAggregateType<T extends CrmSyncEventAggregateArgs> = {
      [P in keyof T & keyof AggregateCrmSyncEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCrmSyncEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateCrmSyncEvent[P]>
}




export type CrmSyncEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CrmSyncEventWhereInput
  orderBy?: Prisma.CrmSyncEventOrderByWithAggregationInput | Prisma.CrmSyncEventOrderByWithAggregationInput[]
  by: Prisma.CrmSyncEventScalarFieldEnum[] | Prisma.CrmSyncEventScalarFieldEnum
  having?: Prisma.CrmSyncEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CrmSyncEventCountAggregateInputType | true
  _min?: CrmSyncEventMinAggregateInputType
  _max?: CrmSyncEventMaxAggregateInputType
}

export type CrmSyncEventGroupByOutputType = {
  id: string
  companyId: string
  status: boolean | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: CrmSyncEventCountAggregateOutputType | null
  _min: CrmSyncEventMinAggregateOutputType | null
  _max: CrmSyncEventMaxAggregateOutputType | null
}

type GetCrmSyncEventGroupByPayload<T extends CrmSyncEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CrmSyncEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CrmSyncEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CrmSyncEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CrmSyncEventGroupByOutputType[P]>
      }
    >
  >



export type CrmSyncEventWhereInput = {
  AND?: Prisma.CrmSyncEventWhereInput | Prisma.CrmSyncEventWhereInput[]
  OR?: Prisma.CrmSyncEventWhereInput[]
  NOT?: Prisma.CrmSyncEventWhereInput | Prisma.CrmSyncEventWhereInput[]
  id?: Prisma.StringFilter<"CrmSyncEvent"> | string
  companyId?: Prisma.StringFilter<"CrmSyncEvent"> | string
  status?: Prisma.BoolNullableFilter<"CrmSyncEvent"> | boolean | null
  notes?: Prisma.StringNullableFilter<"CrmSyncEvent"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CrmSyncEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CrmSyncEvent"> | Date | string
  company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
}

export type CrmSyncEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  company?: Prisma.CompanyOrderByWithRelationInput
}

export type CrmSyncEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  companyId?: string
  AND?: Prisma.CrmSyncEventWhereInput | Prisma.CrmSyncEventWhereInput[]
  OR?: Prisma.CrmSyncEventWhereInput[]
  NOT?: Prisma.CrmSyncEventWhereInput | Prisma.CrmSyncEventWhereInput[]
  status?: Prisma.BoolNullableFilter<"CrmSyncEvent"> | boolean | null
  notes?: Prisma.StringNullableFilter<"CrmSyncEvent"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CrmSyncEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CrmSyncEvent"> | Date | string
  company?: Prisma.XOR<Prisma.CompanyScalarRelationFilter, Prisma.CompanyWhereInput>
}, "id" | "companyId">

export type CrmSyncEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CrmSyncEventCountOrderByAggregateInput
  _max?: Prisma.CrmSyncEventMaxOrderByAggregateInput
  _min?: Prisma.CrmSyncEventMinOrderByAggregateInput
}

export type CrmSyncEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.CrmSyncEventScalarWhereWithAggregatesInput | Prisma.CrmSyncEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.CrmSyncEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CrmSyncEventScalarWhereWithAggregatesInput | Prisma.CrmSyncEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CrmSyncEvent"> | string
  companyId?: Prisma.StringWithAggregatesFilter<"CrmSyncEvent"> | string
  status?: Prisma.BoolNullableWithAggregatesFilter<"CrmSyncEvent"> | boolean | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"CrmSyncEvent"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CrmSyncEvent"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CrmSyncEvent"> | Date | string
}

export type CrmSyncEventCreateInput = {
  id?: string
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  company: Prisma.CompanyCreateNestedOneWithoutCrmSyncEventInput
}

export type CrmSyncEventUncheckedCreateInput = {
  id?: string
  companyId: string
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CrmSyncEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  company?: Prisma.CompanyUpdateOneRequiredWithoutCrmSyncEventNestedInput
}

export type CrmSyncEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrmSyncEventCreateManyInput = {
  id?: string
  companyId: string
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CrmSyncEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrmSyncEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  companyId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrmSyncEventNullableScalarRelationFilter = {
  is?: Prisma.CrmSyncEventWhereInput | null
  isNot?: Prisma.CrmSyncEventWhereInput | null
}

export type CrmSyncEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CrmSyncEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CrmSyncEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  companyId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CrmSyncEventCreateNestedOneWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.CrmSyncEventCreateWithoutCompanyInput, Prisma.CrmSyncEventUncheckedCreateWithoutCompanyInput>
  connectOrCreate?: Prisma.CrmSyncEventCreateOrConnectWithoutCompanyInput
  connect?: Prisma.CrmSyncEventWhereUniqueInput
}

export type CrmSyncEventUncheckedCreateNestedOneWithoutCompanyInput = {
  create?: Prisma.XOR<Prisma.CrmSyncEventCreateWithoutCompanyInput, Prisma.CrmSyncEventUncheckedCreateWithoutCompanyInput>
  connectOrCreate?: Prisma.CrmSyncEventCreateOrConnectWithoutCompanyInput
  connect?: Prisma.CrmSyncEventWhereUniqueInput
}

export type CrmSyncEventUpdateOneWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.CrmSyncEventCreateWithoutCompanyInput, Prisma.CrmSyncEventUncheckedCreateWithoutCompanyInput>
  connectOrCreate?: Prisma.CrmSyncEventCreateOrConnectWithoutCompanyInput
  upsert?: Prisma.CrmSyncEventUpsertWithoutCompanyInput
  disconnect?: Prisma.CrmSyncEventWhereInput | boolean
  delete?: Prisma.CrmSyncEventWhereInput | boolean
  connect?: Prisma.CrmSyncEventWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CrmSyncEventUpdateToOneWithWhereWithoutCompanyInput, Prisma.CrmSyncEventUpdateWithoutCompanyInput>, Prisma.CrmSyncEventUncheckedUpdateWithoutCompanyInput>
}

export type CrmSyncEventUncheckedUpdateOneWithoutCompanyNestedInput = {
  create?: Prisma.XOR<Prisma.CrmSyncEventCreateWithoutCompanyInput, Prisma.CrmSyncEventUncheckedCreateWithoutCompanyInput>
  connectOrCreate?: Prisma.CrmSyncEventCreateOrConnectWithoutCompanyInput
  upsert?: Prisma.CrmSyncEventUpsertWithoutCompanyInput
  disconnect?: Prisma.CrmSyncEventWhereInput | boolean
  delete?: Prisma.CrmSyncEventWhereInput | boolean
  connect?: Prisma.CrmSyncEventWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CrmSyncEventUpdateToOneWithWhereWithoutCompanyInput, Prisma.CrmSyncEventUpdateWithoutCompanyInput>, Prisma.CrmSyncEventUncheckedUpdateWithoutCompanyInput>
}

export type CrmSyncEventCreateWithoutCompanyInput = {
  id?: string
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CrmSyncEventUncheckedCreateWithoutCompanyInput = {
  id?: string
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CrmSyncEventCreateOrConnectWithoutCompanyInput = {
  where: Prisma.CrmSyncEventWhereUniqueInput
  create: Prisma.XOR<Prisma.CrmSyncEventCreateWithoutCompanyInput, Prisma.CrmSyncEventUncheckedCreateWithoutCompanyInput>
}

export type CrmSyncEventUpsertWithoutCompanyInput = {
  update: Prisma.XOR<Prisma.CrmSyncEventUpdateWithoutCompanyInput, Prisma.CrmSyncEventUncheckedUpdateWithoutCompanyInput>
  create: Prisma.XOR<Prisma.CrmSyncEventCreateWithoutCompanyInput, Prisma.CrmSyncEventUncheckedCreateWithoutCompanyInput>
  where?: Prisma.CrmSyncEventWhereInput
}

export type CrmSyncEventUpdateToOneWithWhereWithoutCompanyInput = {
  where?: Prisma.CrmSyncEventWhereInput
  data: Prisma.XOR<Prisma.CrmSyncEventUpdateWithoutCompanyInput, Prisma.CrmSyncEventUncheckedUpdateWithoutCompanyInput>
}

export type CrmSyncEventUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrmSyncEventUncheckedUpdateWithoutCompanyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CrmSyncEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crmSyncEvent"]>

export type CrmSyncEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crmSyncEvent"]>

export type CrmSyncEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  companyId?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crmSyncEvent"]>

export type CrmSyncEventSelectScalar = {
  id?: boolean
  companyId?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CrmSyncEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "companyId" | "status" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["crmSyncEvent"]>
export type CrmSyncEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}
export type CrmSyncEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}
export type CrmSyncEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  company?: boolean | Prisma.CompanyDefaultArgs<ExtArgs>
}

export type $CrmSyncEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CrmSyncEvent"
  objects: {
    company: Prisma.$CompanyPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    companyId: string
    status: boolean | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["crmSyncEvent"]>
  composites: {}
}

export type CrmSyncEventGetPayload<S extends boolean | null | undefined | CrmSyncEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload, S>

export type CrmSyncEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CrmSyncEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CrmSyncEventCountAggregateInputType | true
  }

export interface CrmSyncEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CrmSyncEvent'], meta: { name: 'CrmSyncEvent' } }
  /**
   * Find zero or one CrmSyncEvent that matches the filter.
   * @param {CrmSyncEventFindUniqueArgs} args - Arguments to find a CrmSyncEvent
   * @example
   * // Get one CrmSyncEvent
   * const crmSyncEvent = await prisma.crmSyncEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CrmSyncEventFindUniqueArgs>(args: Prisma.SelectSubset<T, CrmSyncEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CrmSyncEventClient<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CrmSyncEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CrmSyncEventFindUniqueOrThrowArgs} args - Arguments to find a CrmSyncEvent
   * @example
   * // Get one CrmSyncEvent
   * const crmSyncEvent = await prisma.crmSyncEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CrmSyncEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CrmSyncEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CrmSyncEventClient<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CrmSyncEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmSyncEventFindFirstArgs} args - Arguments to find a CrmSyncEvent
   * @example
   * // Get one CrmSyncEvent
   * const crmSyncEvent = await prisma.crmSyncEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CrmSyncEventFindFirstArgs>(args?: Prisma.SelectSubset<T, CrmSyncEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__CrmSyncEventClient<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CrmSyncEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmSyncEventFindFirstOrThrowArgs} args - Arguments to find a CrmSyncEvent
   * @example
   * // Get one CrmSyncEvent
   * const crmSyncEvent = await prisma.crmSyncEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CrmSyncEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CrmSyncEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CrmSyncEventClient<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CrmSyncEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmSyncEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CrmSyncEvents
   * const crmSyncEvents = await prisma.crmSyncEvent.findMany()
   * 
   * // Get first 10 CrmSyncEvents
   * const crmSyncEvents = await prisma.crmSyncEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const crmSyncEventWithIdOnly = await prisma.crmSyncEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CrmSyncEventFindManyArgs>(args?: Prisma.SelectSubset<T, CrmSyncEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CrmSyncEvent.
   * @param {CrmSyncEventCreateArgs} args - Arguments to create a CrmSyncEvent.
   * @example
   * // Create one CrmSyncEvent
   * const CrmSyncEvent = await prisma.crmSyncEvent.create({
   *   data: {
   *     // ... data to create a CrmSyncEvent
   *   }
   * })
   * 
   */
  create<T extends CrmSyncEventCreateArgs>(args: Prisma.SelectSubset<T, CrmSyncEventCreateArgs<ExtArgs>>): Prisma.Prisma__CrmSyncEventClient<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CrmSyncEvents.
   * @param {CrmSyncEventCreateManyArgs} args - Arguments to create many CrmSyncEvents.
   * @example
   * // Create many CrmSyncEvents
   * const crmSyncEvent = await prisma.crmSyncEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CrmSyncEventCreateManyArgs>(args?: Prisma.SelectSubset<T, CrmSyncEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CrmSyncEvents and returns the data saved in the database.
   * @param {CrmSyncEventCreateManyAndReturnArgs} args - Arguments to create many CrmSyncEvents.
   * @example
   * // Create many CrmSyncEvents
   * const crmSyncEvent = await prisma.crmSyncEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CrmSyncEvents and only return the `id`
   * const crmSyncEventWithIdOnly = await prisma.crmSyncEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CrmSyncEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CrmSyncEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CrmSyncEvent.
   * @param {CrmSyncEventDeleteArgs} args - Arguments to delete one CrmSyncEvent.
   * @example
   * // Delete one CrmSyncEvent
   * const CrmSyncEvent = await prisma.crmSyncEvent.delete({
   *   where: {
   *     // ... filter to delete one CrmSyncEvent
   *   }
   * })
   * 
   */
  delete<T extends CrmSyncEventDeleteArgs>(args: Prisma.SelectSubset<T, CrmSyncEventDeleteArgs<ExtArgs>>): Prisma.Prisma__CrmSyncEventClient<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CrmSyncEvent.
   * @param {CrmSyncEventUpdateArgs} args - Arguments to update one CrmSyncEvent.
   * @example
   * // Update one CrmSyncEvent
   * const crmSyncEvent = await prisma.crmSyncEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CrmSyncEventUpdateArgs>(args: Prisma.SelectSubset<T, CrmSyncEventUpdateArgs<ExtArgs>>): Prisma.Prisma__CrmSyncEventClient<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CrmSyncEvents.
   * @param {CrmSyncEventDeleteManyArgs} args - Arguments to filter CrmSyncEvents to delete.
   * @example
   * // Delete a few CrmSyncEvents
   * const { count } = await prisma.crmSyncEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CrmSyncEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, CrmSyncEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CrmSyncEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmSyncEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CrmSyncEvents
   * const crmSyncEvent = await prisma.crmSyncEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CrmSyncEventUpdateManyArgs>(args: Prisma.SelectSubset<T, CrmSyncEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CrmSyncEvents and returns the data updated in the database.
   * @param {CrmSyncEventUpdateManyAndReturnArgs} args - Arguments to update many CrmSyncEvents.
   * @example
   * // Update many CrmSyncEvents
   * const crmSyncEvent = await prisma.crmSyncEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CrmSyncEvents and only return the `id`
   * const crmSyncEventWithIdOnly = await prisma.crmSyncEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CrmSyncEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CrmSyncEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CrmSyncEvent.
   * @param {CrmSyncEventUpsertArgs} args - Arguments to update or create a CrmSyncEvent.
   * @example
   * // Update or create a CrmSyncEvent
   * const crmSyncEvent = await prisma.crmSyncEvent.upsert({
   *   create: {
   *     // ... data to create a CrmSyncEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CrmSyncEvent we want to update
   *   }
   * })
   */
  upsert<T extends CrmSyncEventUpsertArgs>(args: Prisma.SelectSubset<T, CrmSyncEventUpsertArgs<ExtArgs>>): Prisma.Prisma__CrmSyncEventClient<runtime.Types.Result.GetResult<Prisma.$CrmSyncEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CrmSyncEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmSyncEventCountArgs} args - Arguments to filter CrmSyncEvents to count.
   * @example
   * // Count the number of CrmSyncEvents
   * const count = await prisma.crmSyncEvent.count({
   *   where: {
   *     // ... the filter for the CrmSyncEvents we want to count
   *   }
   * })
  **/
  count<T extends CrmSyncEventCountArgs>(
    args?: Prisma.Subset<T, CrmSyncEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CrmSyncEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CrmSyncEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmSyncEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CrmSyncEventAggregateArgs>(args: Prisma.Subset<T, CrmSyncEventAggregateArgs>): Prisma.PrismaPromise<GetCrmSyncEventAggregateType<T>>

  /**
   * Group by CrmSyncEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmSyncEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CrmSyncEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CrmSyncEventGroupByArgs['orderBy'] }
      : { orderBy?: CrmSyncEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CrmSyncEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCrmSyncEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CrmSyncEvent model
 */
readonly fields: CrmSyncEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CrmSyncEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CrmSyncEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  company<T extends Prisma.CompanyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CompanyDefaultArgs<ExtArgs>>): Prisma.Prisma__CompanyClient<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CrmSyncEvent model
 */
export interface CrmSyncEventFieldRefs {
  readonly id: Prisma.FieldRef<"CrmSyncEvent", 'String'>
  readonly companyId: Prisma.FieldRef<"CrmSyncEvent", 'String'>
  readonly status: Prisma.FieldRef<"CrmSyncEvent", 'Boolean'>
  readonly notes: Prisma.FieldRef<"CrmSyncEvent", 'String'>
  readonly createdAt: Prisma.FieldRef<"CrmSyncEvent", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CrmSyncEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CrmSyncEvent findUnique
 */
export type CrmSyncEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * Filter, which CrmSyncEvent to fetch.
   */
  where: Prisma.CrmSyncEventWhereUniqueInput
}

/**
 * CrmSyncEvent findUniqueOrThrow
 */
export type CrmSyncEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * Filter, which CrmSyncEvent to fetch.
   */
  where: Prisma.CrmSyncEventWhereUniqueInput
}

/**
 * CrmSyncEvent findFirst
 */
export type CrmSyncEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * Filter, which CrmSyncEvent to fetch.
   */
  where?: Prisma.CrmSyncEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CrmSyncEvents to fetch.
   */
  orderBy?: Prisma.CrmSyncEventOrderByWithRelationInput | Prisma.CrmSyncEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CrmSyncEvents.
   */
  cursor?: Prisma.CrmSyncEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CrmSyncEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CrmSyncEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CrmSyncEvents.
   */
  distinct?: Prisma.CrmSyncEventScalarFieldEnum | Prisma.CrmSyncEventScalarFieldEnum[]
}

/**
 * CrmSyncEvent findFirstOrThrow
 */
export type CrmSyncEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * Filter, which CrmSyncEvent to fetch.
   */
  where?: Prisma.CrmSyncEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CrmSyncEvents to fetch.
   */
  orderBy?: Prisma.CrmSyncEventOrderByWithRelationInput | Prisma.CrmSyncEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CrmSyncEvents.
   */
  cursor?: Prisma.CrmSyncEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CrmSyncEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CrmSyncEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CrmSyncEvents.
   */
  distinct?: Prisma.CrmSyncEventScalarFieldEnum | Prisma.CrmSyncEventScalarFieldEnum[]
}

/**
 * CrmSyncEvent findMany
 */
export type CrmSyncEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * Filter, which CrmSyncEvents to fetch.
   */
  where?: Prisma.CrmSyncEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CrmSyncEvents to fetch.
   */
  orderBy?: Prisma.CrmSyncEventOrderByWithRelationInput | Prisma.CrmSyncEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CrmSyncEvents.
   */
  cursor?: Prisma.CrmSyncEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CrmSyncEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CrmSyncEvents.
   */
  skip?: number
  distinct?: Prisma.CrmSyncEventScalarFieldEnum | Prisma.CrmSyncEventScalarFieldEnum[]
}

/**
 * CrmSyncEvent create
 */
export type CrmSyncEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * The data needed to create a CrmSyncEvent.
   */
  data: Prisma.XOR<Prisma.CrmSyncEventCreateInput, Prisma.CrmSyncEventUncheckedCreateInput>
}

/**
 * CrmSyncEvent createMany
 */
export type CrmSyncEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CrmSyncEvents.
   */
  data: Prisma.CrmSyncEventCreateManyInput | Prisma.CrmSyncEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CrmSyncEvent createManyAndReturn
 */
export type CrmSyncEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * The data used to create many CrmSyncEvents.
   */
  data: Prisma.CrmSyncEventCreateManyInput | Prisma.CrmSyncEventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CrmSyncEvent update
 */
export type CrmSyncEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * The data needed to update a CrmSyncEvent.
   */
  data: Prisma.XOR<Prisma.CrmSyncEventUpdateInput, Prisma.CrmSyncEventUncheckedUpdateInput>
  /**
   * Choose, which CrmSyncEvent to update.
   */
  where: Prisma.CrmSyncEventWhereUniqueInput
}

/**
 * CrmSyncEvent updateMany
 */
export type CrmSyncEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CrmSyncEvents.
   */
  data: Prisma.XOR<Prisma.CrmSyncEventUpdateManyMutationInput, Prisma.CrmSyncEventUncheckedUpdateManyInput>
  /**
   * Filter which CrmSyncEvents to update
   */
  where?: Prisma.CrmSyncEventWhereInput
  /**
   * Limit how many CrmSyncEvents to update.
   */
  limit?: number
}

/**
 * CrmSyncEvent updateManyAndReturn
 */
export type CrmSyncEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * The data used to update CrmSyncEvents.
   */
  data: Prisma.XOR<Prisma.CrmSyncEventUpdateManyMutationInput, Prisma.CrmSyncEventUncheckedUpdateManyInput>
  /**
   * Filter which CrmSyncEvents to update
   */
  where?: Prisma.CrmSyncEventWhereInput
  /**
   * Limit how many CrmSyncEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CrmSyncEvent upsert
 */
export type CrmSyncEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * The filter to search for the CrmSyncEvent to update in case it exists.
   */
  where: Prisma.CrmSyncEventWhereUniqueInput
  /**
   * In case the CrmSyncEvent found by the `where` argument doesn't exist, create a new CrmSyncEvent with this data.
   */
  create: Prisma.XOR<Prisma.CrmSyncEventCreateInput, Prisma.CrmSyncEventUncheckedCreateInput>
  /**
   * In case the CrmSyncEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CrmSyncEventUpdateInput, Prisma.CrmSyncEventUncheckedUpdateInput>
}

/**
 * CrmSyncEvent delete
 */
export type CrmSyncEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
  /**
   * Filter which CrmSyncEvent to delete.
   */
  where: Prisma.CrmSyncEventWhereUniqueInput
}

/**
 * CrmSyncEvent deleteMany
 */
export type CrmSyncEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CrmSyncEvents to delete
   */
  where?: Prisma.CrmSyncEventWhereInput
  /**
   * Limit how many CrmSyncEvents to delete.
   */
  limit?: number
}

/**
 * CrmSyncEvent without action
 */
export type CrmSyncEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmSyncEvent
   */
  select?: Prisma.CrmSyncEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmSyncEvent
   */
  omit?: Prisma.CrmSyncEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmSyncEventInclude<ExtArgs> | null
}
