
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FirmService` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model FirmService
 * 
 */
export type FirmServiceModel = runtime.Types.Result.DefaultSelection<Prisma.$FirmServicePayload>

export type AggregateFirmService = {
  _count: FirmServiceCountAggregateOutputType | null
  _min: FirmServiceMinAggregateOutputType | null
  _max: FirmServiceMaxAggregateOutputType | null
}

export type FirmServiceMinAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FirmServiceMaxAggregateOutputType = {
  id: string | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FirmServiceCountAggregateOutputType = {
  id: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FirmServiceMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type FirmServiceMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type FirmServiceCountAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FirmServiceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FirmService to aggregate.
   */
  where?: Prisma.FirmServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FirmServices to fetch.
   */
  orderBy?: Prisma.FirmServiceOrderByWithRelationInput | Prisma.FirmServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FirmServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FirmServices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FirmServices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FirmServices
  **/
  _count?: true | FirmServiceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FirmServiceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FirmServiceMaxAggregateInputType
}

export type GetFirmServiceAggregateType<T extends FirmServiceAggregateArgs> = {
      [P in keyof T & keyof AggregateFirmService]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFirmService[P]>
    : Prisma.GetScalarType<T[P], AggregateFirmService[P]>
}




export type FirmServiceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FirmServiceWhereInput
  orderBy?: Prisma.FirmServiceOrderByWithAggregationInput | Prisma.FirmServiceOrderByWithAggregationInput[]
  by: Prisma.FirmServiceScalarFieldEnum[] | Prisma.FirmServiceScalarFieldEnum
  having?: Prisma.FirmServiceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FirmServiceCountAggregateInputType | true
  _min?: FirmServiceMinAggregateInputType
  _max?: FirmServiceMaxAggregateInputType
}

export type FirmServiceGroupByOutputType = {
  id: string
  name: string
  createdAt: Date
  updatedAt: Date
  _count: FirmServiceCountAggregateOutputType | null
  _min: FirmServiceMinAggregateOutputType | null
  _max: FirmServiceMaxAggregateOutputType | null
}

type GetFirmServiceGroupByPayload<T extends FirmServiceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FirmServiceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FirmServiceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FirmServiceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FirmServiceGroupByOutputType[P]>
      }
    >
  >



export type FirmServiceWhereInput = {
  AND?: Prisma.FirmServiceWhereInput | Prisma.FirmServiceWhereInput[]
  OR?: Prisma.FirmServiceWhereInput[]
  NOT?: Prisma.FirmServiceWhereInput | Prisma.FirmServiceWhereInput[]
  id?: Prisma.StringFilter<"FirmService"> | string
  name?: Prisma.StringFilter<"FirmService"> | string
  createdAt?: Prisma.DateTimeFilter<"FirmService"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FirmService"> | Date | string
  companies?: Prisma.CompanyListRelationFilter
}

export type FirmServiceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  companies?: Prisma.CompanyOrderByRelationAggregateInput
}

export type FirmServiceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.FirmServiceWhereInput | Prisma.FirmServiceWhereInput[]
  OR?: Prisma.FirmServiceWhereInput[]
  NOT?: Prisma.FirmServiceWhereInput | Prisma.FirmServiceWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"FirmService"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FirmService"> | Date | string
  companies?: Prisma.CompanyListRelationFilter
}, "id" | "name">

export type FirmServiceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FirmServiceCountOrderByAggregateInput
  _max?: Prisma.FirmServiceMaxOrderByAggregateInput
  _min?: Prisma.FirmServiceMinOrderByAggregateInput
}

export type FirmServiceScalarWhereWithAggregatesInput = {
  AND?: Prisma.FirmServiceScalarWhereWithAggregatesInput | Prisma.FirmServiceScalarWhereWithAggregatesInput[]
  OR?: Prisma.FirmServiceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FirmServiceScalarWhereWithAggregatesInput | Prisma.FirmServiceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FirmService"> | string
  name?: Prisma.StringWithAggregatesFilter<"FirmService"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FirmService"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FirmService"> | Date | string
}

export type FirmServiceCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  companies?: Prisma.CompanyCreateNestedManyWithoutServicesOfferedInput
}

export type FirmServiceUncheckedCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  companies?: Prisma.CompanyUncheckedCreateNestedManyWithoutServicesOfferedInput
}

export type FirmServiceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  companies?: Prisma.CompanyUpdateManyWithoutServicesOfferedNestedInput
}

export type FirmServiceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  companies?: Prisma.CompanyUncheckedUpdateManyWithoutServicesOfferedNestedInput
}

export type FirmServiceCreateManyInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FirmServiceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FirmServiceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FirmServiceListRelationFilter = {
  every?: Prisma.FirmServiceWhereInput
  some?: Prisma.FirmServiceWhereInput
  none?: Prisma.FirmServiceWhereInput
}

export type FirmServiceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FirmServiceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FirmServiceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FirmServiceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FirmServiceCreateNestedManyWithoutCompaniesInput = {
  create?: Prisma.XOR<Prisma.FirmServiceCreateWithoutCompaniesInput, Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput> | Prisma.FirmServiceCreateWithoutCompaniesInput[] | Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput[]
  connectOrCreate?: Prisma.FirmServiceCreateOrConnectWithoutCompaniesInput | Prisma.FirmServiceCreateOrConnectWithoutCompaniesInput[]
  connect?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
}

export type FirmServiceUncheckedCreateNestedManyWithoutCompaniesInput = {
  create?: Prisma.XOR<Prisma.FirmServiceCreateWithoutCompaniesInput, Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput> | Prisma.FirmServiceCreateWithoutCompaniesInput[] | Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput[]
  connectOrCreate?: Prisma.FirmServiceCreateOrConnectWithoutCompaniesInput | Prisma.FirmServiceCreateOrConnectWithoutCompaniesInput[]
  connect?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
}

export type FirmServiceUpdateManyWithoutCompaniesNestedInput = {
  create?: Prisma.XOR<Prisma.FirmServiceCreateWithoutCompaniesInput, Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput> | Prisma.FirmServiceCreateWithoutCompaniesInput[] | Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput[]
  connectOrCreate?: Prisma.FirmServiceCreateOrConnectWithoutCompaniesInput | Prisma.FirmServiceCreateOrConnectWithoutCompaniesInput[]
  upsert?: Prisma.FirmServiceUpsertWithWhereUniqueWithoutCompaniesInput | Prisma.FirmServiceUpsertWithWhereUniqueWithoutCompaniesInput[]
  set?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
  disconnect?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
  delete?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
  connect?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
  update?: Prisma.FirmServiceUpdateWithWhereUniqueWithoutCompaniesInput | Prisma.FirmServiceUpdateWithWhereUniqueWithoutCompaniesInput[]
  updateMany?: Prisma.FirmServiceUpdateManyWithWhereWithoutCompaniesInput | Prisma.FirmServiceUpdateManyWithWhereWithoutCompaniesInput[]
  deleteMany?: Prisma.FirmServiceScalarWhereInput | Prisma.FirmServiceScalarWhereInput[]
}

export type FirmServiceUncheckedUpdateManyWithoutCompaniesNestedInput = {
  create?: Prisma.XOR<Prisma.FirmServiceCreateWithoutCompaniesInput, Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput> | Prisma.FirmServiceCreateWithoutCompaniesInput[] | Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput[]
  connectOrCreate?: Prisma.FirmServiceCreateOrConnectWithoutCompaniesInput | Prisma.FirmServiceCreateOrConnectWithoutCompaniesInput[]
  upsert?: Prisma.FirmServiceUpsertWithWhereUniqueWithoutCompaniesInput | Prisma.FirmServiceUpsertWithWhereUniqueWithoutCompaniesInput[]
  set?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
  disconnect?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
  delete?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
  connect?: Prisma.FirmServiceWhereUniqueInput | Prisma.FirmServiceWhereUniqueInput[]
  update?: Prisma.FirmServiceUpdateWithWhereUniqueWithoutCompaniesInput | Prisma.FirmServiceUpdateWithWhereUniqueWithoutCompaniesInput[]
  updateMany?: Prisma.FirmServiceUpdateManyWithWhereWithoutCompaniesInput | Prisma.FirmServiceUpdateManyWithWhereWithoutCompaniesInput[]
  deleteMany?: Prisma.FirmServiceScalarWhereInput | Prisma.FirmServiceScalarWhereInput[]
}

export type FirmServiceCreateWithoutCompaniesInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FirmServiceUncheckedCreateWithoutCompaniesInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FirmServiceCreateOrConnectWithoutCompaniesInput = {
  where: Prisma.FirmServiceWhereUniqueInput
  create: Prisma.XOR<Prisma.FirmServiceCreateWithoutCompaniesInput, Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput>
}

export type FirmServiceUpsertWithWhereUniqueWithoutCompaniesInput = {
  where: Prisma.FirmServiceWhereUniqueInput
  update: Prisma.XOR<Prisma.FirmServiceUpdateWithoutCompaniesInput, Prisma.FirmServiceUncheckedUpdateWithoutCompaniesInput>
  create: Prisma.XOR<Prisma.FirmServiceCreateWithoutCompaniesInput, Prisma.FirmServiceUncheckedCreateWithoutCompaniesInput>
}

export type FirmServiceUpdateWithWhereUniqueWithoutCompaniesInput = {
  where: Prisma.FirmServiceWhereUniqueInput
  data: Prisma.XOR<Prisma.FirmServiceUpdateWithoutCompaniesInput, Prisma.FirmServiceUncheckedUpdateWithoutCompaniesInput>
}

export type FirmServiceUpdateManyWithWhereWithoutCompaniesInput = {
  where: Prisma.FirmServiceScalarWhereInput
  data: Prisma.XOR<Prisma.FirmServiceUpdateManyMutationInput, Prisma.FirmServiceUncheckedUpdateManyWithoutCompaniesInput>
}

export type FirmServiceScalarWhereInput = {
  AND?: Prisma.FirmServiceScalarWhereInput | Prisma.FirmServiceScalarWhereInput[]
  OR?: Prisma.FirmServiceScalarWhereInput[]
  NOT?: Prisma.FirmServiceScalarWhereInput | Prisma.FirmServiceScalarWhereInput[]
  id?: Prisma.StringFilter<"FirmService"> | string
  name?: Prisma.StringFilter<"FirmService"> | string
  createdAt?: Prisma.DateTimeFilter<"FirmService"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FirmService"> | Date | string
}

export type FirmServiceUpdateWithoutCompaniesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FirmServiceUncheckedUpdateWithoutCompaniesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FirmServiceUncheckedUpdateManyWithoutCompaniesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FirmServiceCountOutputType
 */

export type FirmServiceCountOutputType = {
  companies: number
}

export type FirmServiceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  companies?: boolean | FirmServiceCountOutputTypeCountCompaniesArgs
}

/**
 * FirmServiceCountOutputType without action
 */
export type FirmServiceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmServiceCountOutputType
   */
  select?: Prisma.FirmServiceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FirmServiceCountOutputType without action
 */
export type FirmServiceCountOutputTypeCountCompaniesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CompanyWhereInput
}


export type FirmServiceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  companies?: boolean | Prisma.FirmService$companiesArgs<ExtArgs>
  _count?: boolean | Prisma.FirmServiceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["firmService"]>

export type FirmServiceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["firmService"]>

export type FirmServiceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["firmService"]>

export type FirmServiceSelectScalar = {
  id?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FirmServiceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["firmService"]>
export type FirmServiceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  companies?: boolean | Prisma.FirmService$companiesArgs<ExtArgs>
  _count?: boolean | Prisma.FirmServiceCountOutputTypeDefaultArgs<ExtArgs>
}
export type FirmServiceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FirmServiceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FirmServicePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FirmService"
  objects: {
    companies: Prisma.$CompanyPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["firmService"]>
  composites: {}
}

export type FirmServiceGetPayload<S extends boolean | null | undefined | FirmServiceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FirmServicePayload, S>

export type FirmServiceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FirmServiceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FirmServiceCountAggregateInputType | true
  }

export interface FirmServiceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FirmService'], meta: { name: 'FirmService' } }
  /**
   * Find zero or one FirmService that matches the filter.
   * @param {FirmServiceFindUniqueArgs} args - Arguments to find a FirmService
   * @example
   * // Get one FirmService
   * const firmService = await prisma.firmService.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FirmServiceFindUniqueArgs>(args: Prisma.SelectSubset<T, FirmServiceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FirmServiceClient<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FirmService that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FirmServiceFindUniqueOrThrowArgs} args - Arguments to find a FirmService
   * @example
   * // Get one FirmService
   * const firmService = await prisma.firmService.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FirmServiceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FirmServiceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FirmServiceClient<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FirmService that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FirmServiceFindFirstArgs} args - Arguments to find a FirmService
   * @example
   * // Get one FirmService
   * const firmService = await prisma.firmService.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FirmServiceFindFirstArgs>(args?: Prisma.SelectSubset<T, FirmServiceFindFirstArgs<ExtArgs>>): Prisma.Prisma__FirmServiceClient<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FirmService that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FirmServiceFindFirstOrThrowArgs} args - Arguments to find a FirmService
   * @example
   * // Get one FirmService
   * const firmService = await prisma.firmService.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FirmServiceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FirmServiceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FirmServiceClient<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FirmServices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FirmServiceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FirmServices
   * const firmServices = await prisma.firmService.findMany()
   * 
   * // Get first 10 FirmServices
   * const firmServices = await prisma.firmService.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const firmServiceWithIdOnly = await prisma.firmService.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FirmServiceFindManyArgs>(args?: Prisma.SelectSubset<T, FirmServiceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FirmService.
   * @param {FirmServiceCreateArgs} args - Arguments to create a FirmService.
   * @example
   * // Create one FirmService
   * const FirmService = await prisma.firmService.create({
   *   data: {
   *     // ... data to create a FirmService
   *   }
   * })
   * 
   */
  create<T extends FirmServiceCreateArgs>(args: Prisma.SelectSubset<T, FirmServiceCreateArgs<ExtArgs>>): Prisma.Prisma__FirmServiceClient<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FirmServices.
   * @param {FirmServiceCreateManyArgs} args - Arguments to create many FirmServices.
   * @example
   * // Create many FirmServices
   * const firmService = await prisma.firmService.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FirmServiceCreateManyArgs>(args?: Prisma.SelectSubset<T, FirmServiceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FirmServices and returns the data saved in the database.
   * @param {FirmServiceCreateManyAndReturnArgs} args - Arguments to create many FirmServices.
   * @example
   * // Create many FirmServices
   * const firmService = await prisma.firmService.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FirmServices and only return the `id`
   * const firmServiceWithIdOnly = await prisma.firmService.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FirmServiceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FirmServiceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FirmService.
   * @param {FirmServiceDeleteArgs} args - Arguments to delete one FirmService.
   * @example
   * // Delete one FirmService
   * const FirmService = await prisma.firmService.delete({
   *   where: {
   *     // ... filter to delete one FirmService
   *   }
   * })
   * 
   */
  delete<T extends FirmServiceDeleteArgs>(args: Prisma.SelectSubset<T, FirmServiceDeleteArgs<ExtArgs>>): Prisma.Prisma__FirmServiceClient<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FirmService.
   * @param {FirmServiceUpdateArgs} args - Arguments to update one FirmService.
   * @example
   * // Update one FirmService
   * const firmService = await prisma.firmService.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FirmServiceUpdateArgs>(args: Prisma.SelectSubset<T, FirmServiceUpdateArgs<ExtArgs>>): Prisma.Prisma__FirmServiceClient<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FirmServices.
   * @param {FirmServiceDeleteManyArgs} args - Arguments to filter FirmServices to delete.
   * @example
   * // Delete a few FirmServices
   * const { count } = await prisma.firmService.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FirmServiceDeleteManyArgs>(args?: Prisma.SelectSubset<T, FirmServiceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FirmServices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FirmServiceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FirmServices
   * const firmService = await prisma.firmService.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FirmServiceUpdateManyArgs>(args: Prisma.SelectSubset<T, FirmServiceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FirmServices and returns the data updated in the database.
   * @param {FirmServiceUpdateManyAndReturnArgs} args - Arguments to update many FirmServices.
   * @example
   * // Update many FirmServices
   * const firmService = await prisma.firmService.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FirmServices and only return the `id`
   * const firmServiceWithIdOnly = await prisma.firmService.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FirmServiceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FirmServiceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FirmService.
   * @param {FirmServiceUpsertArgs} args - Arguments to update or create a FirmService.
   * @example
   * // Update or create a FirmService
   * const firmService = await prisma.firmService.upsert({
   *   create: {
   *     // ... data to create a FirmService
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FirmService we want to update
   *   }
   * })
   */
  upsert<T extends FirmServiceUpsertArgs>(args: Prisma.SelectSubset<T, FirmServiceUpsertArgs<ExtArgs>>): Prisma.Prisma__FirmServiceClient<runtime.Types.Result.GetResult<Prisma.$FirmServicePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FirmServices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FirmServiceCountArgs} args - Arguments to filter FirmServices to count.
   * @example
   * // Count the number of FirmServices
   * const count = await prisma.firmService.count({
   *   where: {
   *     // ... the filter for the FirmServices we want to count
   *   }
   * })
  **/
  count<T extends FirmServiceCountArgs>(
    args?: Prisma.Subset<T, FirmServiceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FirmServiceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FirmService.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FirmServiceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FirmServiceAggregateArgs>(args: Prisma.Subset<T, FirmServiceAggregateArgs>): Prisma.PrismaPromise<GetFirmServiceAggregateType<T>>

  /**
   * Group by FirmService.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FirmServiceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FirmServiceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FirmServiceGroupByArgs['orderBy'] }
      : { orderBy?: FirmServiceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FirmServiceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFirmServiceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FirmService model
 */
readonly fields: FirmServiceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FirmService.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FirmServiceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  companies<T extends Prisma.FirmService$companiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FirmService$companiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompanyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FirmService model
 */
export interface FirmServiceFieldRefs {
  readonly id: Prisma.FieldRef<"FirmService", 'String'>
  readonly name: Prisma.FieldRef<"FirmService", 'String'>
  readonly createdAt: Prisma.FieldRef<"FirmService", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FirmService", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FirmService findUnique
 */
export type FirmServiceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * Filter, which FirmService to fetch.
   */
  where: Prisma.FirmServiceWhereUniqueInput
}

/**
 * FirmService findUniqueOrThrow
 */
export type FirmServiceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * Filter, which FirmService to fetch.
   */
  where: Prisma.FirmServiceWhereUniqueInput
}

/**
 * FirmService findFirst
 */
export type FirmServiceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * Filter, which FirmService to fetch.
   */
  where?: Prisma.FirmServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FirmServices to fetch.
   */
  orderBy?: Prisma.FirmServiceOrderByWithRelationInput | Prisma.FirmServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FirmServices.
   */
  cursor?: Prisma.FirmServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FirmServices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FirmServices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FirmServices.
   */
  distinct?: Prisma.FirmServiceScalarFieldEnum | Prisma.FirmServiceScalarFieldEnum[]
}

/**
 * FirmService findFirstOrThrow
 */
export type FirmServiceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * Filter, which FirmService to fetch.
   */
  where?: Prisma.FirmServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FirmServices to fetch.
   */
  orderBy?: Prisma.FirmServiceOrderByWithRelationInput | Prisma.FirmServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FirmServices.
   */
  cursor?: Prisma.FirmServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FirmServices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FirmServices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FirmServices.
   */
  distinct?: Prisma.FirmServiceScalarFieldEnum | Prisma.FirmServiceScalarFieldEnum[]
}

/**
 * FirmService findMany
 */
export type FirmServiceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * Filter, which FirmServices to fetch.
   */
  where?: Prisma.FirmServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FirmServices to fetch.
   */
  orderBy?: Prisma.FirmServiceOrderByWithRelationInput | Prisma.FirmServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FirmServices.
   */
  cursor?: Prisma.FirmServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FirmServices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FirmServices.
   */
  skip?: number
  distinct?: Prisma.FirmServiceScalarFieldEnum | Prisma.FirmServiceScalarFieldEnum[]
}

/**
 * FirmService create
 */
export type FirmServiceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * The data needed to create a FirmService.
   */
  data: Prisma.XOR<Prisma.FirmServiceCreateInput, Prisma.FirmServiceUncheckedCreateInput>
}

/**
 * FirmService createMany
 */
export type FirmServiceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FirmServices.
   */
  data: Prisma.FirmServiceCreateManyInput | Prisma.FirmServiceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FirmService createManyAndReturn
 */
export type FirmServiceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * The data used to create many FirmServices.
   */
  data: Prisma.FirmServiceCreateManyInput | Prisma.FirmServiceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FirmService update
 */
export type FirmServiceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * The data needed to update a FirmService.
   */
  data: Prisma.XOR<Prisma.FirmServiceUpdateInput, Prisma.FirmServiceUncheckedUpdateInput>
  /**
   * Choose, which FirmService to update.
   */
  where: Prisma.FirmServiceWhereUniqueInput
}

/**
 * FirmService updateMany
 */
export type FirmServiceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FirmServices.
   */
  data: Prisma.XOR<Prisma.FirmServiceUpdateManyMutationInput, Prisma.FirmServiceUncheckedUpdateManyInput>
  /**
   * Filter which FirmServices to update
   */
  where?: Prisma.FirmServiceWhereInput
  /**
   * Limit how many FirmServices to update.
   */
  limit?: number
}

/**
 * FirmService updateManyAndReturn
 */
export type FirmServiceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * The data used to update FirmServices.
   */
  data: Prisma.XOR<Prisma.FirmServiceUpdateManyMutationInput, Prisma.FirmServiceUncheckedUpdateManyInput>
  /**
   * Filter which FirmServices to update
   */
  where?: Prisma.FirmServiceWhereInput
  /**
   * Limit how many FirmServices to update.
   */
  limit?: number
}

/**
 * FirmService upsert
 */
export type FirmServiceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * The filter to search for the FirmService to update in case it exists.
   */
  where: Prisma.FirmServiceWhereUniqueInput
  /**
   * In case the FirmService found by the `where` argument doesn't exist, create a new FirmService with this data.
   */
  create: Prisma.XOR<Prisma.FirmServiceCreateInput, Prisma.FirmServiceUncheckedCreateInput>
  /**
   * In case the FirmService was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FirmServiceUpdateInput, Prisma.FirmServiceUncheckedUpdateInput>
}

/**
 * FirmService delete
 */
export type FirmServiceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
  /**
   * Filter which FirmService to delete.
   */
  where: Prisma.FirmServiceWhereUniqueInput
}

/**
 * FirmService deleteMany
 */
export type FirmServiceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FirmServices to delete
   */
  where?: Prisma.FirmServiceWhereInput
  /**
   * Limit how many FirmServices to delete.
   */
  limit?: number
}

/**
 * FirmService.companies
 */
export type FirmService$companiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Company
   */
  select?: Prisma.CompanySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Company
   */
  omit?: Prisma.CompanyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompanyInclude<ExtArgs> | null
  where?: Prisma.CompanyWhereInput
  orderBy?: Prisma.CompanyOrderByWithRelationInput | Prisma.CompanyOrderByWithRelationInput[]
  cursor?: Prisma.CompanyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CompanyScalarFieldEnum | Prisma.CompanyScalarFieldEnum[]
}

/**
 * FirmService without action
 */
export type FirmServiceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FirmService
   */
  select?: Prisma.FirmServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FirmService
   */
  omit?: Prisma.FirmServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FirmServiceInclude<ExtArgs> | null
}
