
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GooglePlaceUrlToScrape` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model GooglePlaceUrlToScrape
 * 
 */
export type GooglePlaceUrlToScrapeModel = runtime.Types.Result.DefaultSelection<Prisma.$GooglePlaceUrlToScrapePayload>

export type AggregateGooglePlaceUrlToScrape = {
  _count: GooglePlaceUrlToScrapeCountAggregateOutputType | null
  _min: GooglePlaceUrlToScrapeMinAggregateOutputType | null
  _max: GooglePlaceUrlToScrapeMaxAggregateOutputType | null
}

export type GooglePlaceUrlToScrapeMinAggregateOutputType = {
  id: string | null
  url: string | null
  location: string | null
  status: boolean | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GooglePlaceUrlToScrapeMaxAggregateOutputType = {
  id: string | null
  url: string | null
  location: string | null
  status: boolean | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type GooglePlaceUrlToScrapeCountAggregateOutputType = {
  id: number
  url: number
  location: number
  status: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type GooglePlaceUrlToScrapeMinAggregateInputType = {
  id?: true
  url?: true
  location?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type GooglePlaceUrlToScrapeMaxAggregateInputType = {
  id?: true
  url?: true
  location?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type GooglePlaceUrlToScrapeCountAggregateInputType = {
  id?: true
  url?: true
  location?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type GooglePlaceUrlToScrapeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GooglePlaceUrlToScrape to aggregate.
   */
  where?: Prisma.GooglePlaceUrlToScrapeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GooglePlaceUrlToScrapes to fetch.
   */
  orderBy?: Prisma.GooglePlaceUrlToScrapeOrderByWithRelationInput | Prisma.GooglePlaceUrlToScrapeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GooglePlaceUrlToScrapes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GooglePlaceUrlToScrapes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GooglePlaceUrlToScrapes
  **/
  _count?: true | GooglePlaceUrlToScrapeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GooglePlaceUrlToScrapeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GooglePlaceUrlToScrapeMaxAggregateInputType
}

export type GetGooglePlaceUrlToScrapeAggregateType<T extends GooglePlaceUrlToScrapeAggregateArgs> = {
      [P in keyof T & keyof AggregateGooglePlaceUrlToScrape]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGooglePlaceUrlToScrape[P]>
    : Prisma.GetScalarType<T[P], AggregateGooglePlaceUrlToScrape[P]>
}




export type GooglePlaceUrlToScrapeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GooglePlaceUrlToScrapeWhereInput
  orderBy?: Prisma.GooglePlaceUrlToScrapeOrderByWithAggregationInput | Prisma.GooglePlaceUrlToScrapeOrderByWithAggregationInput[]
  by: Prisma.GooglePlaceUrlToScrapeScalarFieldEnum[] | Prisma.GooglePlaceUrlToScrapeScalarFieldEnum
  having?: Prisma.GooglePlaceUrlToScrapeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GooglePlaceUrlToScrapeCountAggregateInputType | true
  _min?: GooglePlaceUrlToScrapeMinAggregateInputType
  _max?: GooglePlaceUrlToScrapeMaxAggregateInputType
}

export type GooglePlaceUrlToScrapeGroupByOutputType = {
  id: string
  url: string
  location: string | null
  status: boolean | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: GooglePlaceUrlToScrapeCountAggregateOutputType | null
  _min: GooglePlaceUrlToScrapeMinAggregateOutputType | null
  _max: GooglePlaceUrlToScrapeMaxAggregateOutputType | null
}

type GetGooglePlaceUrlToScrapeGroupByPayload<T extends GooglePlaceUrlToScrapeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GooglePlaceUrlToScrapeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GooglePlaceUrlToScrapeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GooglePlaceUrlToScrapeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GooglePlaceUrlToScrapeGroupByOutputType[P]>
      }
    >
  >



export type GooglePlaceUrlToScrapeWhereInput = {
  AND?: Prisma.GooglePlaceUrlToScrapeWhereInput | Prisma.GooglePlaceUrlToScrapeWhereInput[]
  OR?: Prisma.GooglePlaceUrlToScrapeWhereInput[]
  NOT?: Prisma.GooglePlaceUrlToScrapeWhereInput | Prisma.GooglePlaceUrlToScrapeWhereInput[]
  id?: Prisma.StringFilter<"GooglePlaceUrlToScrape"> | string
  url?: Prisma.StringFilter<"GooglePlaceUrlToScrape"> | string
  location?: Prisma.StringNullableFilter<"GooglePlaceUrlToScrape"> | string | null
  status?: Prisma.BoolNullableFilter<"GooglePlaceUrlToScrape"> | boolean | null
  notes?: Prisma.StringNullableFilter<"GooglePlaceUrlToScrape"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GooglePlaceUrlToScrape"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GooglePlaceUrlToScrape"> | Date | string
}

export type GooglePlaceUrlToScrapeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GooglePlaceUrlToScrapeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  url?: string
  AND?: Prisma.GooglePlaceUrlToScrapeWhereInput | Prisma.GooglePlaceUrlToScrapeWhereInput[]
  OR?: Prisma.GooglePlaceUrlToScrapeWhereInput[]
  NOT?: Prisma.GooglePlaceUrlToScrapeWhereInput | Prisma.GooglePlaceUrlToScrapeWhereInput[]
  location?: Prisma.StringNullableFilter<"GooglePlaceUrlToScrape"> | string | null
  status?: Prisma.BoolNullableFilter<"GooglePlaceUrlToScrape"> | boolean | null
  notes?: Prisma.StringNullableFilter<"GooglePlaceUrlToScrape"> | string | null
  createdAt?: Prisma.DateTimeFilter<"GooglePlaceUrlToScrape"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"GooglePlaceUrlToScrape"> | Date | string
}, "id" | "url">

export type GooglePlaceUrlToScrapeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GooglePlaceUrlToScrapeCountOrderByAggregateInput
  _max?: Prisma.GooglePlaceUrlToScrapeMaxOrderByAggregateInput
  _min?: Prisma.GooglePlaceUrlToScrapeMinOrderByAggregateInput
}

export type GooglePlaceUrlToScrapeScalarWhereWithAggregatesInput = {
  AND?: Prisma.GooglePlaceUrlToScrapeScalarWhereWithAggregatesInput | Prisma.GooglePlaceUrlToScrapeScalarWhereWithAggregatesInput[]
  OR?: Prisma.GooglePlaceUrlToScrapeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GooglePlaceUrlToScrapeScalarWhereWithAggregatesInput | Prisma.GooglePlaceUrlToScrapeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GooglePlaceUrlToScrape"> | string
  url?: Prisma.StringWithAggregatesFilter<"GooglePlaceUrlToScrape"> | string
  location?: Prisma.StringNullableWithAggregatesFilter<"GooglePlaceUrlToScrape"> | string | null
  status?: Prisma.BoolNullableWithAggregatesFilter<"GooglePlaceUrlToScrape"> | boolean | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"GooglePlaceUrlToScrape"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"GooglePlaceUrlToScrape"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GooglePlaceUrlToScrape"> | Date | string
}

export type GooglePlaceUrlToScrapeCreateInput = {
  id?: string
  url: string
  location?: string | null
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GooglePlaceUrlToScrapeUncheckedCreateInput = {
  id?: string
  url: string
  location?: string | null
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GooglePlaceUrlToScrapeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GooglePlaceUrlToScrapeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GooglePlaceUrlToScrapeCreateManyInput = {
  id?: string
  url: string
  location?: string | null
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type GooglePlaceUrlToScrapeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GooglePlaceUrlToScrapeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GooglePlaceUrlToScrapeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  location?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GooglePlaceUrlToScrapeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  location?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GooglePlaceUrlToScrapeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  location?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}



export type GooglePlaceUrlToScrapeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  location?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["googlePlaceUrlToScrape"]>

export type GooglePlaceUrlToScrapeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  location?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["googlePlaceUrlToScrape"]>

export type GooglePlaceUrlToScrapeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  url?: boolean
  location?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["googlePlaceUrlToScrape"]>

export type GooglePlaceUrlToScrapeSelectScalar = {
  id?: boolean
  url?: boolean
  location?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type GooglePlaceUrlToScrapeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "url" | "location" | "status" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["googlePlaceUrlToScrape"]>

export type $GooglePlaceUrlToScrapePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GooglePlaceUrlToScrape"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    url: string
    location: string | null
    status: boolean | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["googlePlaceUrlToScrape"]>
  composites: {}
}

export type GooglePlaceUrlToScrapeGetPayload<S extends boolean | null | undefined | GooglePlaceUrlToScrapeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload, S>

export type GooglePlaceUrlToScrapeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GooglePlaceUrlToScrapeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GooglePlaceUrlToScrapeCountAggregateInputType | true
  }

export interface GooglePlaceUrlToScrapeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GooglePlaceUrlToScrape'], meta: { name: 'GooglePlaceUrlToScrape' } }
  /**
   * Find zero or one GooglePlaceUrlToScrape that matches the filter.
   * @param {GooglePlaceUrlToScrapeFindUniqueArgs} args - Arguments to find a GooglePlaceUrlToScrape
   * @example
   * // Get one GooglePlaceUrlToScrape
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GooglePlaceUrlToScrapeFindUniqueArgs>(args: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GooglePlaceUrlToScrapeClient<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GooglePlaceUrlToScrape that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GooglePlaceUrlToScrapeFindUniqueOrThrowArgs} args - Arguments to find a GooglePlaceUrlToScrape
   * @example
   * // Get one GooglePlaceUrlToScrape
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GooglePlaceUrlToScrapeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GooglePlaceUrlToScrapeClient<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GooglePlaceUrlToScrape that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GooglePlaceUrlToScrapeFindFirstArgs} args - Arguments to find a GooglePlaceUrlToScrape
   * @example
   * // Get one GooglePlaceUrlToScrape
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GooglePlaceUrlToScrapeFindFirstArgs>(args?: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeFindFirstArgs<ExtArgs>>): Prisma.Prisma__GooglePlaceUrlToScrapeClient<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GooglePlaceUrlToScrape that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GooglePlaceUrlToScrapeFindFirstOrThrowArgs} args - Arguments to find a GooglePlaceUrlToScrape
   * @example
   * // Get one GooglePlaceUrlToScrape
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GooglePlaceUrlToScrapeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GooglePlaceUrlToScrapeClient<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GooglePlaceUrlToScrapes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GooglePlaceUrlToScrapeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GooglePlaceUrlToScrapes
   * const googlePlaceUrlToScrapes = await prisma.googlePlaceUrlToScrape.findMany()
   * 
   * // Get first 10 GooglePlaceUrlToScrapes
   * const googlePlaceUrlToScrapes = await prisma.googlePlaceUrlToScrape.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const googlePlaceUrlToScrapeWithIdOnly = await prisma.googlePlaceUrlToScrape.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GooglePlaceUrlToScrapeFindManyArgs>(args?: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GooglePlaceUrlToScrape.
   * @param {GooglePlaceUrlToScrapeCreateArgs} args - Arguments to create a GooglePlaceUrlToScrape.
   * @example
   * // Create one GooglePlaceUrlToScrape
   * const GooglePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.create({
   *   data: {
   *     // ... data to create a GooglePlaceUrlToScrape
   *   }
   * })
   * 
   */
  create<T extends GooglePlaceUrlToScrapeCreateArgs>(args: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeCreateArgs<ExtArgs>>): Prisma.Prisma__GooglePlaceUrlToScrapeClient<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GooglePlaceUrlToScrapes.
   * @param {GooglePlaceUrlToScrapeCreateManyArgs} args - Arguments to create many GooglePlaceUrlToScrapes.
   * @example
   * // Create many GooglePlaceUrlToScrapes
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GooglePlaceUrlToScrapeCreateManyArgs>(args?: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GooglePlaceUrlToScrapes and returns the data saved in the database.
   * @param {GooglePlaceUrlToScrapeCreateManyAndReturnArgs} args - Arguments to create many GooglePlaceUrlToScrapes.
   * @example
   * // Create many GooglePlaceUrlToScrapes
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GooglePlaceUrlToScrapes and only return the `id`
   * const googlePlaceUrlToScrapeWithIdOnly = await prisma.googlePlaceUrlToScrape.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GooglePlaceUrlToScrapeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GooglePlaceUrlToScrape.
   * @param {GooglePlaceUrlToScrapeDeleteArgs} args - Arguments to delete one GooglePlaceUrlToScrape.
   * @example
   * // Delete one GooglePlaceUrlToScrape
   * const GooglePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.delete({
   *   where: {
   *     // ... filter to delete one GooglePlaceUrlToScrape
   *   }
   * })
   * 
   */
  delete<T extends GooglePlaceUrlToScrapeDeleteArgs>(args: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeDeleteArgs<ExtArgs>>): Prisma.Prisma__GooglePlaceUrlToScrapeClient<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GooglePlaceUrlToScrape.
   * @param {GooglePlaceUrlToScrapeUpdateArgs} args - Arguments to update one GooglePlaceUrlToScrape.
   * @example
   * // Update one GooglePlaceUrlToScrape
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GooglePlaceUrlToScrapeUpdateArgs>(args: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeUpdateArgs<ExtArgs>>): Prisma.Prisma__GooglePlaceUrlToScrapeClient<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GooglePlaceUrlToScrapes.
   * @param {GooglePlaceUrlToScrapeDeleteManyArgs} args - Arguments to filter GooglePlaceUrlToScrapes to delete.
   * @example
   * // Delete a few GooglePlaceUrlToScrapes
   * const { count } = await prisma.googlePlaceUrlToScrape.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GooglePlaceUrlToScrapeDeleteManyArgs>(args?: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GooglePlaceUrlToScrapes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GooglePlaceUrlToScrapeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GooglePlaceUrlToScrapes
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GooglePlaceUrlToScrapeUpdateManyArgs>(args: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GooglePlaceUrlToScrapes and returns the data updated in the database.
   * @param {GooglePlaceUrlToScrapeUpdateManyAndReturnArgs} args - Arguments to update many GooglePlaceUrlToScrapes.
   * @example
   * // Update many GooglePlaceUrlToScrapes
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GooglePlaceUrlToScrapes and only return the `id`
   * const googlePlaceUrlToScrapeWithIdOnly = await prisma.googlePlaceUrlToScrape.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GooglePlaceUrlToScrapeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GooglePlaceUrlToScrape.
   * @param {GooglePlaceUrlToScrapeUpsertArgs} args - Arguments to update or create a GooglePlaceUrlToScrape.
   * @example
   * // Update or create a GooglePlaceUrlToScrape
   * const googlePlaceUrlToScrape = await prisma.googlePlaceUrlToScrape.upsert({
   *   create: {
   *     // ... data to create a GooglePlaceUrlToScrape
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GooglePlaceUrlToScrape we want to update
   *   }
   * })
   */
  upsert<T extends GooglePlaceUrlToScrapeUpsertArgs>(args: Prisma.SelectSubset<T, GooglePlaceUrlToScrapeUpsertArgs<ExtArgs>>): Prisma.Prisma__GooglePlaceUrlToScrapeClient<runtime.Types.Result.GetResult<Prisma.$GooglePlaceUrlToScrapePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GooglePlaceUrlToScrapes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GooglePlaceUrlToScrapeCountArgs} args - Arguments to filter GooglePlaceUrlToScrapes to count.
   * @example
   * // Count the number of GooglePlaceUrlToScrapes
   * const count = await prisma.googlePlaceUrlToScrape.count({
   *   where: {
   *     // ... the filter for the GooglePlaceUrlToScrapes we want to count
   *   }
   * })
  **/
  count<T extends GooglePlaceUrlToScrapeCountArgs>(
    args?: Prisma.Subset<T, GooglePlaceUrlToScrapeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GooglePlaceUrlToScrapeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GooglePlaceUrlToScrape.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GooglePlaceUrlToScrapeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GooglePlaceUrlToScrapeAggregateArgs>(args: Prisma.Subset<T, GooglePlaceUrlToScrapeAggregateArgs>): Prisma.PrismaPromise<GetGooglePlaceUrlToScrapeAggregateType<T>>

  /**
   * Group by GooglePlaceUrlToScrape.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GooglePlaceUrlToScrapeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GooglePlaceUrlToScrapeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GooglePlaceUrlToScrapeGroupByArgs['orderBy'] }
      : { orderBy?: GooglePlaceUrlToScrapeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GooglePlaceUrlToScrapeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGooglePlaceUrlToScrapeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GooglePlaceUrlToScrape model
 */
readonly fields: GooglePlaceUrlToScrapeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GooglePlaceUrlToScrape.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GooglePlaceUrlToScrapeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GooglePlaceUrlToScrape model
 */
export interface GooglePlaceUrlToScrapeFieldRefs {
  readonly id: Prisma.FieldRef<"GooglePlaceUrlToScrape", 'String'>
  readonly url: Prisma.FieldRef<"GooglePlaceUrlToScrape", 'String'>
  readonly location: Prisma.FieldRef<"GooglePlaceUrlToScrape", 'String'>
  readonly status: Prisma.FieldRef<"GooglePlaceUrlToScrape", 'Boolean'>
  readonly notes: Prisma.FieldRef<"GooglePlaceUrlToScrape", 'String'>
  readonly createdAt: Prisma.FieldRef<"GooglePlaceUrlToScrape", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GooglePlaceUrlToScrape", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GooglePlaceUrlToScrape findUnique
 */
export type GooglePlaceUrlToScrapeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * Filter, which GooglePlaceUrlToScrape to fetch.
   */
  where: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
}

/**
 * GooglePlaceUrlToScrape findUniqueOrThrow
 */
export type GooglePlaceUrlToScrapeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * Filter, which GooglePlaceUrlToScrape to fetch.
   */
  where: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
}

/**
 * GooglePlaceUrlToScrape findFirst
 */
export type GooglePlaceUrlToScrapeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * Filter, which GooglePlaceUrlToScrape to fetch.
   */
  where?: Prisma.GooglePlaceUrlToScrapeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GooglePlaceUrlToScrapes to fetch.
   */
  orderBy?: Prisma.GooglePlaceUrlToScrapeOrderByWithRelationInput | Prisma.GooglePlaceUrlToScrapeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GooglePlaceUrlToScrapes.
   */
  cursor?: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GooglePlaceUrlToScrapes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GooglePlaceUrlToScrapes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GooglePlaceUrlToScrapes.
   */
  distinct?: Prisma.GooglePlaceUrlToScrapeScalarFieldEnum | Prisma.GooglePlaceUrlToScrapeScalarFieldEnum[]
}

/**
 * GooglePlaceUrlToScrape findFirstOrThrow
 */
export type GooglePlaceUrlToScrapeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * Filter, which GooglePlaceUrlToScrape to fetch.
   */
  where?: Prisma.GooglePlaceUrlToScrapeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GooglePlaceUrlToScrapes to fetch.
   */
  orderBy?: Prisma.GooglePlaceUrlToScrapeOrderByWithRelationInput | Prisma.GooglePlaceUrlToScrapeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GooglePlaceUrlToScrapes.
   */
  cursor?: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GooglePlaceUrlToScrapes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GooglePlaceUrlToScrapes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GooglePlaceUrlToScrapes.
   */
  distinct?: Prisma.GooglePlaceUrlToScrapeScalarFieldEnum | Prisma.GooglePlaceUrlToScrapeScalarFieldEnum[]
}

/**
 * GooglePlaceUrlToScrape findMany
 */
export type GooglePlaceUrlToScrapeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * Filter, which GooglePlaceUrlToScrapes to fetch.
   */
  where?: Prisma.GooglePlaceUrlToScrapeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GooglePlaceUrlToScrapes to fetch.
   */
  orderBy?: Prisma.GooglePlaceUrlToScrapeOrderByWithRelationInput | Prisma.GooglePlaceUrlToScrapeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GooglePlaceUrlToScrapes.
   */
  cursor?: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GooglePlaceUrlToScrapes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GooglePlaceUrlToScrapes.
   */
  skip?: number
  distinct?: Prisma.GooglePlaceUrlToScrapeScalarFieldEnum | Prisma.GooglePlaceUrlToScrapeScalarFieldEnum[]
}

/**
 * GooglePlaceUrlToScrape create
 */
export type GooglePlaceUrlToScrapeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * The data needed to create a GooglePlaceUrlToScrape.
   */
  data: Prisma.XOR<Prisma.GooglePlaceUrlToScrapeCreateInput, Prisma.GooglePlaceUrlToScrapeUncheckedCreateInput>
}

/**
 * GooglePlaceUrlToScrape createMany
 */
export type GooglePlaceUrlToScrapeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GooglePlaceUrlToScrapes.
   */
  data: Prisma.GooglePlaceUrlToScrapeCreateManyInput | Prisma.GooglePlaceUrlToScrapeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GooglePlaceUrlToScrape createManyAndReturn
 */
export type GooglePlaceUrlToScrapeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * The data used to create many GooglePlaceUrlToScrapes.
   */
  data: Prisma.GooglePlaceUrlToScrapeCreateManyInput | Prisma.GooglePlaceUrlToScrapeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GooglePlaceUrlToScrape update
 */
export type GooglePlaceUrlToScrapeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * The data needed to update a GooglePlaceUrlToScrape.
   */
  data: Prisma.XOR<Prisma.GooglePlaceUrlToScrapeUpdateInput, Prisma.GooglePlaceUrlToScrapeUncheckedUpdateInput>
  /**
   * Choose, which GooglePlaceUrlToScrape to update.
   */
  where: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
}

/**
 * GooglePlaceUrlToScrape updateMany
 */
export type GooglePlaceUrlToScrapeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GooglePlaceUrlToScrapes.
   */
  data: Prisma.XOR<Prisma.GooglePlaceUrlToScrapeUpdateManyMutationInput, Prisma.GooglePlaceUrlToScrapeUncheckedUpdateManyInput>
  /**
   * Filter which GooglePlaceUrlToScrapes to update
   */
  where?: Prisma.GooglePlaceUrlToScrapeWhereInput
  /**
   * Limit how many GooglePlaceUrlToScrapes to update.
   */
  limit?: number
}

/**
 * GooglePlaceUrlToScrape updateManyAndReturn
 */
export type GooglePlaceUrlToScrapeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * The data used to update GooglePlaceUrlToScrapes.
   */
  data: Prisma.XOR<Prisma.GooglePlaceUrlToScrapeUpdateManyMutationInput, Prisma.GooglePlaceUrlToScrapeUncheckedUpdateManyInput>
  /**
   * Filter which GooglePlaceUrlToScrapes to update
   */
  where?: Prisma.GooglePlaceUrlToScrapeWhereInput
  /**
   * Limit how many GooglePlaceUrlToScrapes to update.
   */
  limit?: number
}

/**
 * GooglePlaceUrlToScrape upsert
 */
export type GooglePlaceUrlToScrapeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * The filter to search for the GooglePlaceUrlToScrape to update in case it exists.
   */
  where: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
  /**
   * In case the GooglePlaceUrlToScrape found by the `where` argument doesn't exist, create a new GooglePlaceUrlToScrape with this data.
   */
  create: Prisma.XOR<Prisma.GooglePlaceUrlToScrapeCreateInput, Prisma.GooglePlaceUrlToScrapeUncheckedCreateInput>
  /**
   * In case the GooglePlaceUrlToScrape was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GooglePlaceUrlToScrapeUpdateInput, Prisma.GooglePlaceUrlToScrapeUncheckedUpdateInput>
}

/**
 * GooglePlaceUrlToScrape delete
 */
export type GooglePlaceUrlToScrapeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
  /**
   * Filter which GooglePlaceUrlToScrape to delete.
   */
  where: Prisma.GooglePlaceUrlToScrapeWhereUniqueInput
}

/**
 * GooglePlaceUrlToScrape deleteMany
 */
export type GooglePlaceUrlToScrapeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GooglePlaceUrlToScrapes to delete
   */
  where?: Prisma.GooglePlaceUrlToScrapeWhereInput
  /**
   * Limit how many GooglePlaceUrlToScrapes to delete.
   */
  limit?: number
}

/**
 * GooglePlaceUrlToScrape without action
 */
export type GooglePlaceUrlToScrapeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GooglePlaceUrlToScrape
   */
  select?: Prisma.GooglePlaceUrlToScrapeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GooglePlaceUrlToScrape
   */
  omit?: Prisma.GooglePlaceUrlToScrapeOmit<ExtArgs> | null
}
