
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PlaceEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model PlaceEntry
 * 
 */
export type PlaceEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$PlaceEntryPayload>

export type AggregatePlaceEntry = {
  _count: PlaceEntryCountAggregateOutputType | null
  _min: PlaceEntryMinAggregateOutputType | null
  _max: PlaceEntryMaxAggregateOutputType | null
}

export type PlaceEntryMinAggregateOutputType = {
  id: string | null
  name: string | null
  url: string | null
  address: string | null
  telephone: string | null
  location: string | null
  status: boolean | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlaceEntryMaxAggregateOutputType = {
  id: string | null
  name: string | null
  url: string | null
  address: string | null
  telephone: string | null
  location: string | null
  status: boolean | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlaceEntryCountAggregateOutputType = {
  id: number
  name: number
  url: number
  address: number
  telephone: number
  location: number
  status: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PlaceEntryMinAggregateInputType = {
  id?: true
  name?: true
  url?: true
  address?: true
  telephone?: true
  location?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type PlaceEntryMaxAggregateInputType = {
  id?: true
  name?: true
  url?: true
  address?: true
  telephone?: true
  location?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type PlaceEntryCountAggregateInputType = {
  id?: true
  name?: true
  url?: true
  address?: true
  telephone?: true
  location?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PlaceEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlaceEntry to aggregate.
   */
  where?: Prisma.PlaceEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaceEntries to fetch.
   */
  orderBy?: Prisma.PlaceEntryOrderByWithRelationInput | Prisma.PlaceEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlaceEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaceEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaceEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PlaceEntries
  **/
  _count?: true | PlaceEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlaceEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlaceEntryMaxAggregateInputType
}

export type GetPlaceEntryAggregateType<T extends PlaceEntryAggregateArgs> = {
      [P in keyof T & keyof AggregatePlaceEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlaceEntry[P]>
    : Prisma.GetScalarType<T[P], AggregatePlaceEntry[P]>
}




export type PlaceEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaceEntryWhereInput
  orderBy?: Prisma.PlaceEntryOrderByWithAggregationInput | Prisma.PlaceEntryOrderByWithAggregationInput[]
  by: Prisma.PlaceEntryScalarFieldEnum[] | Prisma.PlaceEntryScalarFieldEnum
  having?: Prisma.PlaceEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlaceEntryCountAggregateInputType | true
  _min?: PlaceEntryMinAggregateInputType
  _max?: PlaceEntryMaxAggregateInputType
}

export type PlaceEntryGroupByOutputType = {
  id: string
  name: string | null
  url: string
  address: string | null
  telephone: string | null
  location: string | null
  status: boolean | null
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: PlaceEntryCountAggregateOutputType | null
  _min: PlaceEntryMinAggregateOutputType | null
  _max: PlaceEntryMaxAggregateOutputType | null
}

type GetPlaceEntryGroupByPayload<T extends PlaceEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlaceEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlaceEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlaceEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlaceEntryGroupByOutputType[P]>
      }
    >
  >



export type PlaceEntryWhereInput = {
  AND?: Prisma.PlaceEntryWhereInput | Prisma.PlaceEntryWhereInput[]
  OR?: Prisma.PlaceEntryWhereInput[]
  NOT?: Prisma.PlaceEntryWhereInput | Prisma.PlaceEntryWhereInput[]
  id?: Prisma.StringFilter<"PlaceEntry"> | string
  name?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  url?: Prisma.StringFilter<"PlaceEntry"> | string
  address?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  telephone?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  location?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  status?: Prisma.BoolNullableFilter<"PlaceEntry"> | boolean | null
  notes?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PlaceEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PlaceEntry"> | Date | string
}

export type PlaceEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  telephone?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaceEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  url?: string
  AND?: Prisma.PlaceEntryWhereInput | Prisma.PlaceEntryWhereInput[]
  OR?: Prisma.PlaceEntryWhereInput[]
  NOT?: Prisma.PlaceEntryWhereInput | Prisma.PlaceEntryWhereInput[]
  name?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  address?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  telephone?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  location?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  status?: Prisma.BoolNullableFilter<"PlaceEntry"> | boolean | null
  notes?: Prisma.StringNullableFilter<"PlaceEntry"> | string | null
  createdAt?: Prisma.DateTimeFilter<"PlaceEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PlaceEntry"> | Date | string
}, "id" | "url">

export type PlaceEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  telephone?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PlaceEntryCountOrderByAggregateInput
  _max?: Prisma.PlaceEntryMaxOrderByAggregateInput
  _min?: Prisma.PlaceEntryMinOrderByAggregateInput
}

export type PlaceEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlaceEntryScalarWhereWithAggregatesInput | Prisma.PlaceEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlaceEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlaceEntryScalarWhereWithAggregatesInput | Prisma.PlaceEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PlaceEntry"> | string
  name?: Prisma.StringNullableWithAggregatesFilter<"PlaceEntry"> | string | null
  url?: Prisma.StringWithAggregatesFilter<"PlaceEntry"> | string
  address?: Prisma.StringNullableWithAggregatesFilter<"PlaceEntry"> | string | null
  telephone?: Prisma.StringNullableWithAggregatesFilter<"PlaceEntry"> | string | null
  location?: Prisma.StringNullableWithAggregatesFilter<"PlaceEntry"> | string | null
  status?: Prisma.BoolNullableWithAggregatesFilter<"PlaceEntry"> | boolean | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"PlaceEntry"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PlaceEntry"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PlaceEntry"> | Date | string
}

export type PlaceEntryCreateInput = {
  id?: string
  name?: string | null
  url: string
  address?: string | null
  telephone?: string | null
  location?: string | null
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaceEntryUncheckedCreateInput = {
  id?: string
  name?: string | null
  url: string
  address?: string | null
  telephone?: string | null
  location?: string | null
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaceEntryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  telephone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaceEntryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  telephone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaceEntryCreateManyInput = {
  id?: string
  name?: string | null
  url: string
  address?: string | null
  telephone?: string | null
  location?: string | null
  status?: boolean | null
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaceEntryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  telephone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaceEntryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  telephone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaceEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  address?: Prisma.SortOrder
  telephone?: Prisma.SortOrder
  location?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaceEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  address?: Prisma.SortOrder
  telephone?: Prisma.SortOrder
  location?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaceEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  url?: Prisma.SortOrder
  address?: Prisma.SortOrder
  telephone?: Prisma.SortOrder
  location?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type PlaceEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  url?: boolean
  address?: boolean
  telephone?: boolean
  location?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["placeEntry"]>

export type PlaceEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  url?: boolean
  address?: boolean
  telephone?: boolean
  location?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["placeEntry"]>

export type PlaceEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  url?: boolean
  address?: boolean
  telephone?: boolean
  location?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["placeEntry"]>

export type PlaceEntrySelectScalar = {
  id?: boolean
  name?: boolean
  url?: boolean
  address?: boolean
  telephone?: boolean
  location?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PlaceEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "url" | "address" | "telephone" | "location" | "status" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["placeEntry"]>

export type $PlaceEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PlaceEntry"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string | null
    url: string
    address: string | null
    telephone: string | null
    location: string | null
    status: boolean | null
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["placeEntry"]>
  composites: {}
}

export type PlaceEntryGetPayload<S extends boolean | null | undefined | PlaceEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload, S>

export type PlaceEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlaceEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlaceEntryCountAggregateInputType | true
  }

export interface PlaceEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PlaceEntry'], meta: { name: 'PlaceEntry' } }
  /**
   * Find zero or one PlaceEntry that matches the filter.
   * @param {PlaceEntryFindUniqueArgs} args - Arguments to find a PlaceEntry
   * @example
   * // Get one PlaceEntry
   * const placeEntry = await prisma.placeEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlaceEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, PlaceEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlaceEntryClient<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PlaceEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlaceEntryFindUniqueOrThrowArgs} args - Arguments to find a PlaceEntry
   * @example
   * // Get one PlaceEntry
   * const placeEntry = await prisma.placeEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlaceEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlaceEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaceEntryClient<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlaceEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceEntryFindFirstArgs} args - Arguments to find a PlaceEntry
   * @example
   * // Get one PlaceEntry
   * const placeEntry = await prisma.placeEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlaceEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, PlaceEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlaceEntryClient<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlaceEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceEntryFindFirstOrThrowArgs} args - Arguments to find a PlaceEntry
   * @example
   * // Get one PlaceEntry
   * const placeEntry = await prisma.placeEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlaceEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlaceEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaceEntryClient<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PlaceEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PlaceEntries
   * const placeEntries = await prisma.placeEntry.findMany()
   * 
   * // Get first 10 PlaceEntries
   * const placeEntries = await prisma.placeEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const placeEntryWithIdOnly = await prisma.placeEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlaceEntryFindManyArgs>(args?: Prisma.SelectSubset<T, PlaceEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PlaceEntry.
   * @param {PlaceEntryCreateArgs} args - Arguments to create a PlaceEntry.
   * @example
   * // Create one PlaceEntry
   * const PlaceEntry = await prisma.placeEntry.create({
   *   data: {
   *     // ... data to create a PlaceEntry
   *   }
   * })
   * 
   */
  create<T extends PlaceEntryCreateArgs>(args: Prisma.SelectSubset<T, PlaceEntryCreateArgs<ExtArgs>>): Prisma.Prisma__PlaceEntryClient<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PlaceEntries.
   * @param {PlaceEntryCreateManyArgs} args - Arguments to create many PlaceEntries.
   * @example
   * // Create many PlaceEntries
   * const placeEntry = await prisma.placeEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlaceEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, PlaceEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PlaceEntries and returns the data saved in the database.
   * @param {PlaceEntryCreateManyAndReturnArgs} args - Arguments to create many PlaceEntries.
   * @example
   * // Create many PlaceEntries
   * const placeEntry = await prisma.placeEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PlaceEntries and only return the `id`
   * const placeEntryWithIdOnly = await prisma.placeEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlaceEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlaceEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PlaceEntry.
   * @param {PlaceEntryDeleteArgs} args - Arguments to delete one PlaceEntry.
   * @example
   * // Delete one PlaceEntry
   * const PlaceEntry = await prisma.placeEntry.delete({
   *   where: {
   *     // ... filter to delete one PlaceEntry
   *   }
   * })
   * 
   */
  delete<T extends PlaceEntryDeleteArgs>(args: Prisma.SelectSubset<T, PlaceEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__PlaceEntryClient<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PlaceEntry.
   * @param {PlaceEntryUpdateArgs} args - Arguments to update one PlaceEntry.
   * @example
   * // Update one PlaceEntry
   * const placeEntry = await prisma.placeEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlaceEntryUpdateArgs>(args: Prisma.SelectSubset<T, PlaceEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__PlaceEntryClient<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PlaceEntries.
   * @param {PlaceEntryDeleteManyArgs} args - Arguments to filter PlaceEntries to delete.
   * @example
   * // Delete a few PlaceEntries
   * const { count } = await prisma.placeEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlaceEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlaceEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlaceEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PlaceEntries
   * const placeEntry = await prisma.placeEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlaceEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, PlaceEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlaceEntries and returns the data updated in the database.
   * @param {PlaceEntryUpdateManyAndReturnArgs} args - Arguments to update many PlaceEntries.
   * @example
   * // Update many PlaceEntries
   * const placeEntry = await prisma.placeEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PlaceEntries and only return the `id`
   * const placeEntryWithIdOnly = await prisma.placeEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlaceEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlaceEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PlaceEntry.
   * @param {PlaceEntryUpsertArgs} args - Arguments to update or create a PlaceEntry.
   * @example
   * // Update or create a PlaceEntry
   * const placeEntry = await prisma.placeEntry.upsert({
   *   create: {
   *     // ... data to create a PlaceEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PlaceEntry we want to update
   *   }
   * })
   */
  upsert<T extends PlaceEntryUpsertArgs>(args: Prisma.SelectSubset<T, PlaceEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__PlaceEntryClient<runtime.Types.Result.GetResult<Prisma.$PlaceEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PlaceEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceEntryCountArgs} args - Arguments to filter PlaceEntries to count.
   * @example
   * // Count the number of PlaceEntries
   * const count = await prisma.placeEntry.count({
   *   where: {
   *     // ... the filter for the PlaceEntries we want to count
   *   }
   * })
  **/
  count<T extends PlaceEntryCountArgs>(
    args?: Prisma.Subset<T, PlaceEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlaceEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PlaceEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlaceEntryAggregateArgs>(args: Prisma.Subset<T, PlaceEntryAggregateArgs>): Prisma.PrismaPromise<GetPlaceEntryAggregateType<T>>

  /**
   * Group by PlaceEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlaceEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlaceEntryGroupByArgs['orderBy'] }
      : { orderBy?: PlaceEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlaceEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlaceEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PlaceEntry model
 */
readonly fields: PlaceEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PlaceEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlaceEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PlaceEntry model
 */
export interface PlaceEntryFieldRefs {
  readonly id: Prisma.FieldRef<"PlaceEntry", 'String'>
  readonly name: Prisma.FieldRef<"PlaceEntry", 'String'>
  readonly url: Prisma.FieldRef<"PlaceEntry", 'String'>
  readonly address: Prisma.FieldRef<"PlaceEntry", 'String'>
  readonly telephone: Prisma.FieldRef<"PlaceEntry", 'String'>
  readonly location: Prisma.FieldRef<"PlaceEntry", 'String'>
  readonly status: Prisma.FieldRef<"PlaceEntry", 'Boolean'>
  readonly notes: Prisma.FieldRef<"PlaceEntry", 'String'>
  readonly createdAt: Prisma.FieldRef<"PlaceEntry", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PlaceEntry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PlaceEntry findUnique
 */
export type PlaceEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * Filter, which PlaceEntry to fetch.
   */
  where: Prisma.PlaceEntryWhereUniqueInput
}

/**
 * PlaceEntry findUniqueOrThrow
 */
export type PlaceEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * Filter, which PlaceEntry to fetch.
   */
  where: Prisma.PlaceEntryWhereUniqueInput
}

/**
 * PlaceEntry findFirst
 */
export type PlaceEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * Filter, which PlaceEntry to fetch.
   */
  where?: Prisma.PlaceEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaceEntries to fetch.
   */
  orderBy?: Prisma.PlaceEntryOrderByWithRelationInput | Prisma.PlaceEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlaceEntries.
   */
  cursor?: Prisma.PlaceEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaceEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaceEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaceEntries.
   */
  distinct?: Prisma.PlaceEntryScalarFieldEnum | Prisma.PlaceEntryScalarFieldEnum[]
}

/**
 * PlaceEntry findFirstOrThrow
 */
export type PlaceEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * Filter, which PlaceEntry to fetch.
   */
  where?: Prisma.PlaceEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaceEntries to fetch.
   */
  orderBy?: Prisma.PlaceEntryOrderByWithRelationInput | Prisma.PlaceEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlaceEntries.
   */
  cursor?: Prisma.PlaceEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaceEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaceEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlaceEntries.
   */
  distinct?: Prisma.PlaceEntryScalarFieldEnum | Prisma.PlaceEntryScalarFieldEnum[]
}

/**
 * PlaceEntry findMany
 */
export type PlaceEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * Filter, which PlaceEntries to fetch.
   */
  where?: Prisma.PlaceEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlaceEntries to fetch.
   */
  orderBy?: Prisma.PlaceEntryOrderByWithRelationInput | Prisma.PlaceEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PlaceEntries.
   */
  cursor?: Prisma.PlaceEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlaceEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlaceEntries.
   */
  skip?: number
  distinct?: Prisma.PlaceEntryScalarFieldEnum | Prisma.PlaceEntryScalarFieldEnum[]
}

/**
 * PlaceEntry create
 */
export type PlaceEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * The data needed to create a PlaceEntry.
   */
  data: Prisma.XOR<Prisma.PlaceEntryCreateInput, Prisma.PlaceEntryUncheckedCreateInput>
}

/**
 * PlaceEntry createMany
 */
export type PlaceEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PlaceEntries.
   */
  data: Prisma.PlaceEntryCreateManyInput | Prisma.PlaceEntryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlaceEntry createManyAndReturn
 */
export type PlaceEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * The data used to create many PlaceEntries.
   */
  data: Prisma.PlaceEntryCreateManyInput | Prisma.PlaceEntryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlaceEntry update
 */
export type PlaceEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * The data needed to update a PlaceEntry.
   */
  data: Prisma.XOR<Prisma.PlaceEntryUpdateInput, Prisma.PlaceEntryUncheckedUpdateInput>
  /**
   * Choose, which PlaceEntry to update.
   */
  where: Prisma.PlaceEntryWhereUniqueInput
}

/**
 * PlaceEntry updateMany
 */
export type PlaceEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PlaceEntries.
   */
  data: Prisma.XOR<Prisma.PlaceEntryUpdateManyMutationInput, Prisma.PlaceEntryUncheckedUpdateManyInput>
  /**
   * Filter which PlaceEntries to update
   */
  where?: Prisma.PlaceEntryWhereInput
  /**
   * Limit how many PlaceEntries to update.
   */
  limit?: number
}

/**
 * PlaceEntry updateManyAndReturn
 */
export type PlaceEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * The data used to update PlaceEntries.
   */
  data: Prisma.XOR<Prisma.PlaceEntryUpdateManyMutationInput, Prisma.PlaceEntryUncheckedUpdateManyInput>
  /**
   * Filter which PlaceEntries to update
   */
  where?: Prisma.PlaceEntryWhereInput
  /**
   * Limit how many PlaceEntries to update.
   */
  limit?: number
}

/**
 * PlaceEntry upsert
 */
export type PlaceEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * The filter to search for the PlaceEntry to update in case it exists.
   */
  where: Prisma.PlaceEntryWhereUniqueInput
  /**
   * In case the PlaceEntry found by the `where` argument doesn't exist, create a new PlaceEntry with this data.
   */
  create: Prisma.XOR<Prisma.PlaceEntryCreateInput, Prisma.PlaceEntryUncheckedCreateInput>
  /**
   * In case the PlaceEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlaceEntryUpdateInput, Prisma.PlaceEntryUncheckedUpdateInput>
}

/**
 * PlaceEntry delete
 */
export type PlaceEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
  /**
   * Filter which PlaceEntry to delete.
   */
  where: Prisma.PlaceEntryWhereUniqueInput
}

/**
 * PlaceEntry deleteMany
 */
export type PlaceEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlaceEntries to delete
   */
  where?: Prisma.PlaceEntryWhereInput
  /**
   * Limit how many PlaceEntries to delete.
   */
  limit?: number
}

/**
 * PlaceEntry without action
 */
export type PlaceEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlaceEntry
   */
  select?: Prisma.PlaceEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlaceEntry
   */
  omit?: Prisma.PlaceEntryOmit<ExtArgs> | null
}
