
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model GooglePlaceUrlToScrape
 * 
 */
export type GooglePlaceUrlToScrape = Prisma.GooglePlaceUrlToScrapeModel
/**
 * Model PlaceEntry
 * 
 */
export type PlaceEntry = Prisma.PlaceEntryModel
/**
 * Model Company
 * 
 */
export type Company = Prisma.CompanyModel
/**
 * Model FirmService
 * 
 */
export type FirmService = Prisma.FirmServiceModel
/**
 * Model CrmSyncEvent
 * 
 */
export type CrmSyncEvent = Prisma.CrmSyncEventModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
