
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more GooglePlaceUrlToScrapes
 * const googlePlaceUrlToScrapes = await prisma.googlePlaceUrlToScrape.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model GooglePlaceUrlToScrape
 * 
 */
export type GooglePlaceUrlToScrape = Prisma.GooglePlaceUrlToScrapeModel
/**
 * Model PlaceEntry
 * 
 */
export type PlaceEntry = Prisma.PlaceEntryModel
/**
 * Model Company
 * 
 */
export type Company = Prisma.CompanyModel
/**
 * Model FirmService
 * 
 */
export type FirmService = Prisma.FirmServiceModel
/**
 * Model CrmSyncEvent
 * 
 */
export type CrmSyncEvent = Prisma.CrmSyncEventModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
