
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const EnumServiceName = {
  Places_Locator: 'Places_Locator',
  Website_Content_Scrapper: 'Website_Content_Scrapper',
  CRM_Sync: 'CRM_Sync'
} as const

export type EnumServiceName = (typeof EnumServiceName)[keyof typeof EnumServiceName]
